package io.github.supermonster003.autojs6.plugin.three.maple.image

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import android.graphics.pdf.PdfRenderer
import android.graphics.drawable.BitmapDrawable
import android.os.CancellationSignal
import android.os.OperationCanceledException
import android.os.ParcelFileDescriptor
import android.print.PrintAttributes
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.runner.AndroidJUnit4
import java.io.ByteArrayOutputStream
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotSame
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ImagePrintPdfInstrumentationTest {

    @Test
    fun snapshotOwnsItsBitmapAndReleasesItIdempotently() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val source = twoColorLandscapeBitmap()
        val snapshot = requireNotNull(
            ImagePrintSnapshot.capture(BitmapDrawable(context.resources, source), 1),
        )

        assertNotSame(source, snapshot.bitmap)
        assertEquals(source.height, snapshot.outputWidth)
        assertEquals(source.width, snapshot.outputHeight)
        source.recycle()
        assertFalse(snapshot.bitmap.isRecycled)

        snapshot.close()
        snapshot.close()
        assertTrue(snapshot.bitmap.isRecycled)
    }

    @Test
    fun writesRotatedSinglePagePdfInMemoryWithoutCreatingPluginFiles() {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val targetContext = instrumentation.targetContext
        val source = twoColorLandscapeBitmap()
        val snapshot = requireNotNull(
            ImagePrintSnapshot.capture(
                BitmapDrawable(targetContext.resources, source),
                rotationQuarterTurns = 1,
            ),
        )
        source.recycle()

        val beforeFiles = pluginPrivateFiles(targetContext)
        val output = ByteArrayOutputStream()
        try {
            ImagePrintPdfWriter.write(
                context = targetContext,
                attributes = portraitPrintAttributes(),
                snapshot = snapshot,
                output = output,
                cancellationSignal = CancellationSignal(),
            )
            val pdfBytes = output.toByteArray()
            assertTrue(pdfBytes.size > 500)
            assertTrue(pdfBytes.copyOfRange(0, 5).decodeToString() == "%PDF-")
            assertTrue(pdfBytes.decodeToString().trimEnd().endsWith("%%EOF"))
            assertEquals(beforeFiles, pluginPrivateFiles(targetContext))

            assertRenderedClockwiseOrientation(
                pdfBytes = pdfBytes,
                validationContext = targetContext,
            )
        } finally {
            snapshot.close()
        }
    }

    @Test
    fun preCancelledWriteProducesNoPdfOrPrivateFiles() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val source = twoColorLandscapeBitmap()
        val snapshot = requireNotNull(
            ImagePrintSnapshot.capture(BitmapDrawable(context.resources, source), 0),
        )
        source.recycle()
        val output = ByteArrayOutputStream()
        val cancellationSignal = CancellationSignal().apply { cancel() }
        val beforeFiles = pluginPrivateFiles(context)
        try {
            try {
                ImagePrintPdfWriter.write(
                    context = context,
                    attributes = portraitPrintAttributes(),
                    snapshot = snapshot,
                    output = output,
                    cancellationSignal = cancellationSignal,
                )
                fail("A pre-cancelled write must stop before creating a PDF")
            } catch (_: OperationCanceledException) {
                // Expected: the cancellation check happens before allocating the PDF document.
            }
            assertEquals(0, output.size())
            assertEquals(beforeFiles, pluginPrivateFiles(context))
        } finally {
            snapshot.close()
        }
    }

    private fun assertRenderedClockwiseOrientation(
        pdfBytes: ByteArray,
        validationContext: Context,
    ) {
        val validationDirectory = validationContext.cacheDir.apply {
            check(isDirectory || mkdirs()) { "The test-only PDF validation directory is unavailable" }
        }
        // This file is created only after the no-product-files assertion above. PdfRenderer needs
        // a seekable descriptor, so the test persists its already-generated bytes and removes them
        // immediately after pixel validation; the production writer never receives a File.
        val pdfFile = File.createTempFile("image-print-render-", ".pdf", validationDirectory)
        try {
            pdfFile.writeBytes(pdfBytes)
            ParcelFileDescriptor.open(pdfFile, ParcelFileDescriptor.MODE_READ_ONLY).use { descriptor ->
                PdfRenderer(descriptor).use { renderer ->
                    assertEquals(1, renderer.pageCount)
                    renderer.openPage(0).use { page ->
                        val rendered = Bitmap.createBitmap(
                            page.width,
                            page.height,
                            Bitmap.Config.ARGB_8888,
                        )
                        try {
                            rendered.eraseColor(Color.WHITE)
                            page.render(
                                rendered,
                                null,
                                null,
                                PdfRenderer.Page.RENDER_MODE_FOR_PRINT,
                            )
                            assertMostlyRed(rendered.getPixel(page.width / 2, page.height / 4))
                            assertMostlyBlue(rendered.getPixel(page.width / 2, page.height * 3 / 4))
                        } finally {
                            rendered.recycle()
                        }
                    }
                }
            }
        } finally {
            assertTrue(pdfFile.delete() || !pdfFile.exists())
        }
    }

    private fun twoColorLandscapeBitmap(): Bitmap =
        Bitmap.createBitmap(40, 20, Bitmap.Config.ARGB_8888).also { bitmap ->
            for (y in 0 until bitmap.height) {
                for (x in 0 until bitmap.width) {
                    bitmap.setPixel(x, y, if (x < bitmap.width / 2) Color.RED else Color.BLUE)
                }
            }
        }

    private fun portraitPrintAttributes(): PrintAttributes = PrintAttributes.Builder()
        .setMediaSize(PrintAttributes.MediaSize.ISO_A4.asPortrait())
        .setResolution(PrintAttributes.Resolution("test", "Test", 300, 300))
        .setMinMargins(PrintAttributes.Margins.NO_MARGINS)
        .setColorMode(PrintAttributes.COLOR_MODE_COLOR)
        .build()

    private fun pluginPrivateFiles(context: Context): Map<String, Pair<Long, Long>> =
        listOf(context.cacheDir, context.filesDir)
            .flatMap { root ->
                root.walkTopDown()
                    .filter(File::isFile)
                    .mapNotNull { file ->
                        val relativePath = file.relativeTo(context.dataDir).invariantSeparatorsPath
                        relativePath.takeUnless(::isFrameworkManagedPrivateFile)?.let {
                            it to (file.length() to file.lastModified())
                        }
                    }
                    .toList()
            }
            .toMap()

    private fun isFrameworkManagedPrivateFile(relativePath: String): Boolean =
        relativePath == "files/profileInstalled" ||
            relativePath.startsWith("cache/image_manager_disk_cache/")

    private fun assertMostlyRed(color: Int) {
        assertTrue("Expected red but was #${color.toUInt().toString(16)}", Color.red(color) > 220)
        assertTrue(Color.green(color) < 40)
        assertTrue(Color.blue(color) < 40)
    }

    private fun assertMostlyBlue(color: Int) {
        assertTrue("Expected blue but was #${color.toUInt().toString(16)}", Color.blue(color) > 220)
        assertTrue(Color.red(color) < 40)
        assertTrue(Color.green(color) < 40)
    }
}
